menu:
    Blog: /
    Archiv: /archives
    Info: /info
    Kontakt: /kontakt
#    GitHub:
    Rss: /atom.xml

favicon: /favicon.ico
logo: /dev/log $<span class="cursor">_</span>

# Comment
# e.g disqus: seansun
disqus: devlogblog	
duoshuo:
livere:

# Analytics
# google-analytics:
ga: UA-112049936-1

# Copyright Infomation
startyear: 2018

# Styles shoule be found in the list: https://highlightjs.org/static/demo/
# use the lowercase letters and replace space with -
codestyle: monokai
